const enum BoneName {
    all_body = 'all-body',
    spine1 = 'spine1',
    spine2 = 'spine2',
    spine3 = 'spine3',
    neck = 'neck',
    head = 'head',
    left_shoulder = 'left-shoulder',
    right_shoulder = 'right-shoulder',

    left_top_arm = 'left-top-arm',
    right_top_arm = 'right-top-arm',
    left_bottom_arm = 'left-bottom-arm',
    right_bottom_arm = 'right-bottom-arm',

    left_wrist = 'left-wrist',
    right_wrist = 'right-wrist',

    left_1_1 = "left-1-1",
    right_1_1 = "right-1-1",
    left_2_1 = "left-2-1",
    right_2_1 = "right-2-1",
    left_3_1 = "left-3-1",
    right_3_1 = "right-3-1",
    left_4_1 = "left-4-1",
    right_4_1 = "right-4-1",
    left_5_1 = "left-5-1",
    right_5_1 = "right-5-1",

    left_1_2 = "left-1-2",
    right_1_2 = "right-1-2",
    left_2_2 = "left-2-2",
    right_2_2 = "right-2-2",
    left_3_2 = "left-3-2",
    right_3_2 = "right-3-2",
    left_4_2 = "left-4-2",
    right_4_2 = "right-4-2",
    left_5_2 = "left-5-2",
    right_5_2 = "right-5-2",

    left_1_3 = "left-1-3",
    right_1_3 = "right-1-3",
    left_2_3 = "left-2-3",
    right_2_3 = "right-2-3",
    left_3_3 = "left-3-3",
    right_3_3 = "right-3-3",
    left_4_3 = "left-4-3",
    right_4_3 = "right-4-3",
    left_5_3 = "left-5-3",
    right_5_3 = "right-5-3",

    left_1_4 = "left-1-4",
    right_1_4 = "right-1-4",
    left_2_4 = "left-2-4",
    right_2_4 = "right-2-4",
    left_3_4 = "left-3-4",
    right_3_4 = "right-3-4",
    left_4_4 = "left-4-4",
    right_4_4 = "right-4-4",
    left_5_4 = "left-5-4",
    right_5_4 = "right-5-4",

    left_top_leg = "left-top-leg",
    right_top_leg = "right-top-leg",

    left_bottom_leg = "left-bottom-leg",
    right_bottom_leg = "right-bottom-leg",

    left_ankle = "left-ankle",
    right_ankle = "right-ankle",
    
    left_toe = "left-toe",
    right_toe = "right-toe",
}
export default BoneName